spring.application.name=glpi_spring

# sqlite 
spring.datasource.url=jdbc:sqlite:C:\Users\ACER NITRO\Music\Farany\glpi_spring\dolibarr.db
spring.datasource.driver-class-name=org.sqlite.JDBC

#hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=update

server.servlet.context-path=/dolibarr-backend